### ISSUE TITLE
Implement Material Design for the movie listings

### ISSUE THREAD

**Issue by panwarab** [AbhirojPanwar/Popular_Movies_Stage_2#1]
App as of know, contains basic grid UI (A grid view) to display movie elements. 

-->> Target is to make the grid UI such that It gains a bit more material feels.

-->> any small change to the look and feel will aslo do (marking a small step towards the goal).

**Comment by ayush9** [comment]
api key not available. showing error:
{"status_code":7,"status_message":"Invalid API key: You must be granted a valid key."}

**Comment by panwarab** [comment]
@ayush9 go through readme.md please.

**Comment by rrishabhj** [comment]
hey is the issue still open?

**Comment by panwarab** [comment]
@rrishabhj no.
